version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - "type:enhancement"
      - "area:protocol"
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      codeql-action:
        applies-to: version-updates
        patterns:
          - "github/codeql-action/*"
    labels:
      - "type:enhancement"
    open-pull-requests-limit: 5
